Fix typo in SCSI definition
MissionCriticalCloud/cosmic pull request #563
Opened 2017-12-08 09:38 UTC by remibergsma

Backport from ACS PR 2341

2017-12-08 12:25 UTC, remibergsma commented
go build

2017-12-08 16:19 UTC, remibergsma commented
go build

2017-12-11 19:35 UTC, remibergsma commented
go build

2017-12-12 07:28 UTC, borisroman requested changes
Pending codestyle fixes

2017-12-12 18:06 UTC, borisroman approved these changes

2017-12-13 07:47 UTC, merged