Limit static route result to corresponding vpcId when a gwId is passed
MissionCriticalCloud/cosmic pull request #90
Opened 2016-10-04 14:02 UTC by remibergsma

When a private `gatewayId` is passed, lookup its `VPCid` and return only static routes that belong to this VPC.

2016-10-04 18:45 UTC, borisroman requested changes

2016-10-04 18:45 UTC, borisroman commented on cosmic-core/api/src/main/java/org/apache/cloudstack/api/command/user/vpc/ListStaticRoutesCmd.java
> +            return gateway.getVpcId();
`gateway` can be null here when a non existing private gateway id has been used. Please review @remibergsma

2016-10-05 06:08 UTC, remibergsma commented on cosmic-core/api/src/main/java/org/apache/cloudstack/api/command/user/vpc/ListStaticRoutesCmd.java
> +            return gateway.getVpcId();
Thanks @borisroman will have a look at it

2016-10-05 10:10 UTC, remibergsma commented
go build

2016-10-05 21:05 UTC, remibergsma commented
go build

2016-10-06 08:56 UTC, merged